/**
 * OCF Core — generated markdown reports (membership ledger + R5 gap report).
 *
 * Shared by the build (scripts/derive-core-build, which WRITES them into core/)
 * and the CI check (scripts/derive-core-check, which RE-RENDERS and diffs them
 * against the committed copies) so the two can never disagree on the text — the
 * same drift guarantee the schema package already enjoys. Pure functions of a
 * `Derived`; no I/O.
 */
import { Derived } from "./core-pipeline.js";
import { BOOKKEEPING, buildTargetIndex } from "./report-helpers.js";
import {
  FlowRow,
  byObjectTables,
  flowMapLines,
  groupByEntity,
  groupByVariant,
  mermaidFlow,
} from "./report-flow.js";

// ---------------------------------------------------------------------------
// Membership ledger.
// ---------------------------------------------------------------------------

export function renderLedger(d: Derived): string {
  const aliasEntities = new Set(
    d.corpus.objects.filter((object) => object.aliasOf).map((object) => object.entity)
  );
  const admBy = new Map(
    d.admissibility
      .filter((a) => !aliasEntities.has(a.entity))
      .map((a) => [`${a.entity} ${a.variant}`, a])
  );
  const lines: string[] = [
    "# OCF Core — membership ledger (generated)",
    "",
    "GENERATED by scripts/derive-core-build — do not hand-edit; re-derived on every",
    "build and pinned by `npm run core:check`. One row per `(entity, variant, field)`.",
    "",
    "## Admissibility (§3)",
    "",
    "Compatibility-wrapper aliases are detected internally for admissibility, but are",
    "not standalone Core entities: their economic mapping lives on the canonical base.",
    "",
    "Compatibility wrappers (`PlanSecurity*`) are intentionally omitted from the generated",
    "field and admissibility tables below. Their economic fields are inherited from the",
    "corresponding `EquityCompensation*` mapping; the wrapper schemas remain in the source",
    "corpus for legacy discriminator compatibility.",
    "",
    "| entity | variant | core | payload | admissible | blockers |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const a of d.admissibility.filter((row) => !aliasEntities.has(row.entity))) {
    const blk = a.blockers
      .map((b) =>
        b.why === "no-payload"
          ? "no-payload"
          : b.why === "alias"
          ? `alias-of ${b.referent}`
          : `${b.field}→${b.referent}`
      )
      .join(", ");
    lines.push(
      `| ${a.entity} | ${a.variant} | ${a.coreFieldCount} | ${a.payloadFieldCount} | ${
        a.admissible ? "✓" : "✗"
      } | ${blk || "—"} |`
    );
  }

  // Composite folds (§4.9): transactions with no single Carta target that fold
  // into an ordered SET of Carta transactions. Surfaced so the docs make clear
  // which mappings compose and through which Carta objects.
  const composites = d.corpus.objects.filter((o) => o.composite && o.composite.length > 0);
  if (composites.length > 0) {
    lines.push(
      "",
      "## Composite folds (§4.9)",
      "",
      "Transactions that fold into an ordered SET of Carta transactions (all emitted,",
      "unlike mutually-exclusive variants). Each step names the Carta object(s) it lands",
      "on — the target diverges by family where the step `$def` does — and the fixed",
      "values its `const:` supplies implicitly (the reason codes we always know).",
      "",
      "| entity | step | Carta object(s) | fixed values (const) |",
      "| --- | --- | --- | --- |"
    );
    for (const o of composites) {
      for (const s of o.composite!) {
        const objs = s.targets.map((t) => `\`${t}\``).join(", ") || "—";
        const fixed =
          [
            ...new Set(
              Object.values(s.fills)
                .flat()
                .map((f) => `${f.prop}=${f.value}`)
            ),
          ]
            .sort()
            .join(", ") || "—";
        lines.push(`| ${o.entity} | ${s.step} | ${objs} | ${fixed} |`);
      }
    }
  }

  // Deferred mappings (future investigation): fields carrying a `defer:` placeholder —
  // a complex object whose nested content IS mappable but isn't extracted yet. A tracked
  // backlog so the gap is explicit, not silent.
  const deferred = d.corpus.objects.filter((o) => o.deferrals.length > 0);
  if (deferred.length > 0) {
    lines.push(
      "",
      "## Deferred mappings (future investigation)",
      "",
      "Fields left partially mapped BY DESIGN for now: a complex object carries nested content",
      "that IS mappable but needs extraction we haven't built. `would fill` names the Carta slots",
      'a future nested extraction could populate — those read as "deferred", not "no OCF source",',
      "in the coverage report.",
      "",
      "| entity | field | would fill (Carta) | note |",
      "| --- | --- | --- | --- |"
    );
    for (const o of deferred) {
      for (const dn of o.deferrals) {
        const fills =
          dn.targets
            .map((t) => `\`${t.replace(/^#\/\$defs\//, "").replace("/properties/", ".")}\``)
            .join(", ") || "—";
        lines.push(
          `| ${o.entity} | ${dn.field} | ${fills} | ${dn.note.replace(/\s+/g, " ").trim()} |`
        );
      }
    }
  }

  lines.push(
    "",
    "## Fields (§2)",
    "",
    "| entity | variant | field | class | loss/reason | detail |",
    "| --- | --- | --- | --- | --- | --- |"
  );
  for (const r of d.rows.filter((row) => !aliasEntities.has(row.entity))) {
    const v = r.verdict;
    const lr = v.class === "core" ? v.loss ?? "" : v.reason ?? "";
    const detail = [v.detail, v.review ? `⚑ ${v.review}` : ""].filter(Boolean).join("; ");
    const admitted = admBy.get(`${r.entity} ${r.variant}`)?.admissible ? "" : " ";
    lines.push(
      `| ${r.entity}${admitted} | ${r.variant} | ${r.field} | ${v.class} | ${lr} | ${detail} |`
    );
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// R5 gap report.
// ---------------------------------------------------------------------------

export function renderGapReport(d: Derived): string {
  const admissible = new Map(d.admissibility.map((a) => [`${a.entity} ${a.variant}`, a]));
  const reqByEntity = new Map(d.corpus.objects.map((o) => [o.entity, new Set(o.requiredFields)]));
  const targetOf = buildTargetIndex(d.corpus.objects);

  // The section-(a) casualties as flow rows, for the diagram: `out`, not a heuristic
  // reverse-edge (kept for the upstream report), not bookkeeping, on an admissible
  // entity. `existence-loss` fields have a (lossy) Carta home; `no-destination` have
  // none and drain to the sink.
  const gapRows: FlowRow[] = [];
  for (const r of d.rows) {
    const reason = r.verdict.reason;
    if (r.verdict.class !== "out" || reason === undefined) continue;
    if (reason === "heuristic" || BOOKKEEPING.has(r.field)) continue;
    if (!admissible.get(`${r.entity} ${r.variant}`)?.admissible) continue;
    gapRows.push({
      entity: r.entity,
      variant: r.variant,
      field: r.field,
      reason,
      detail: r.verdict.detail ?? "",
      target: targetOf.get(`${r.entity} ${r.variant} ${r.field}`) ?? "—",
      ocfRequired: reqByEntity.get(r.entity)?.has(r.field) ?? false,
      admissible: true,
    });
  }

  const lines: string[] = [
    "# OCF Core — gap report (R5, generated)",
    "",
    "GENERATED by scripts/derive-core-build. (a) OCF richness with no Carta home,",
    "per admissible entity, OCF-*required* casualties **bold**; (b) Carta inverse",
    "coverage by slot and object-definition role.",
    "",
    "## (a) OCF richness dropped on fold-down",
    "",
    "One diagram per OCF object — each polymorphic flavor (`Object [Variant]`) fully separate:",
    "`existence-loss` fields narrow onto a Carta object; `no-destination` fields have no home and",
    "drop to that flavor's own `⌀ no Carta home` sink. Edge labels = field count.",
    "(Reverse-edge `heuristic` lineage is the upstream report's.)",
    "",
    ...mermaidFlow(groupByVariant(gapRows), { sink: "⌀ no Carta home" }),
    "",
  ];

  const nodes = new Map<string, typeof d.rows>();
  for (const r of d.rows) {
    const k = `${r.entity} ${r.variant}`;
    const list = nodes.get(k) ?? [];
    list.push(r);
    nodes.set(k, list);
  }

  for (const [key, frs] of [...nodes.entries()].sort()) {
    if (!admissible.get(key)?.admissible) continue;
    const out = frs.filter(
      (r) =>
        r.verdict.class === "out" && r.verdict.reason !== "heuristic" && !BOOKKEEPING.has(r.field)
    );
    if (out.length === 0) continue;
    const req = reqByEntity.get(frs[0]!.entity) ?? new Set<string>();
    const label =
      frs[0]!.variant === "—" ? frs[0]!.entity : `${frs[0]!.entity} [${frs[0]!.variant}]`;
    lines.push(`### ${label}`);
    for (const r of out.sort((a, b) => a.field.localeCompare(b.field))) {
      const tag = `${r.verdict.reason}${r.verdict.detail ? ` — ${r.verdict.detail}` : ""}`;
      const name = req.has(r.field) ? `**${r.field}** (OCF-required)` : r.field;
      lines.push(`- ${name}: ${tag}`);
    }
    lines.push("");
  }

  lines.push("## (b) Carta inverse coverage by object definition", "");
  lines.push(
    "The canonical target-first inverse report owns the Carta-side object panels, source paths,",
    "role policy, open-question projection, and visual flow artifacts. This Core gap report does",
    "not reproduce that ledger or maintain a second target-side summary.",
    "",
    "The same `renderMappingInverseReport` renderer is materialized by `npm run mapping:artifacts`.",
    "See `docs/generated/mapping-inverse-report.md` and `docs/generated/mapping-flows/` for the",
    "complete target-first evidence and visuals.",
    ""
  );
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Upstream-OCF change report (rich profile only).
// ---------------------------------------------------------------------------

/**
 * The fields rich-Core admits in OCF's own shape but that the target can only
 * hold in a NARROWED form (`existence-loss` = structure/array flattened to a
 * scalar; `heuristic` = combine/split/computed). Two consequences follow and
 * this report is the actionable list of both:
 *   · Core→target is lossy here (the target narrows the OCF shape) — expected.
 *   · Core→OCF may be invalid for a TARGET-SOURCED Core doc: e.g. Carta supplies
 *     only an address `country`, but OCF's `Address` requires more. Making the
 *     round-trip valid needs OCF to relax the constraint upstream — the candidates
 *     are listed here, OCF-*required* casualties flagged as the strongest asks.
 * Empty for the strict profile (no lossy members).
 */
export function renderUpstreamReport(d: Derived): string {
  const admissible = new Set(
    d.admissibility.filter((a) => a.admissible).map((a) => `${a.entity} ${a.variant}`)
  );
  const reqByEntity = new Map(d.corpus.objects.map((o) => [o.entity, new Set(o.requiredFields)]));
  const targetOf = buildTargetIndex(d.corpus.objects);

  const rows: FlowRow[] = [];
  for (const r of d.rows) {
    const reason = r.verdict.reason;
    if (r.verdict.class !== "out" || reason === undefined) continue;
    if (!d.profile.memberReasons.has(reason)) continue; // only this profile's lossy members
    if (BOOKKEEPING.has(r.field)) continue;
    if (!admissible.has(`${r.entity} ${r.variant}`)) continue; // only fields Core actually carries
    rows.push({
      entity: r.entity,
      variant: r.variant,
      field: r.field,
      reason,
      detail: r.verdict.detail ?? "",
      target: targetOf.get(`${r.entity} ${r.variant} ${r.field}`) ?? "—",
      ocfRequired: reqByEntity.get(r.entity)?.has(r.field) ?? false,
      admissible: true, // filtered to admissible above
    });
  }
  const groups = groupByEntity(rows);
  const diagramGroups = groupByVariant(rows); // diagrams split polymorphic flavors apart
  const reqCount = rows.filter((r) => r.ocfRequired).length;

  const lines: string[] = [
    `# OCF Core (${d.profile.name}) — upstream-OCF change candidates (generated)`,
    "",
    "GENERATED by scripts/derive-core-build — do not hand-edit; pinned by `core:check`.",
    "",
    "rich-Core keeps these fields in **OCF's own shape**; the target can only hold a",
    "narrowed form. So Core→target is lossy (expected), and a target-sourced Core doc",
    "may not validate back as OCF without OCF relaxing a constraint. These are the",
    "upstream-OCF-change candidates; OCF-*required* fields (**bold**) are the strongest.",
    "",
    `## Overview — where rich-Core's lossy fields flow (${rows.length} fields, ${reqCount} OCF-required)`,
    "",
    "One diagram per OCF object — each polymorphic flavor (`Object [Variant]`) fully separate — with",
    "the Carta objects it lands on. Edge labels = the property flowing; cross-object convergence",
    "(several sources on one Carta slot) is in the flow map below.",
    "",
    ...(rows.length
      ? mermaidFlow(diagramGroups)
      : ["(none — this profile carries no lossy-home fields.)"]),
    "",
    "## By OCF object — each field and its narrowed Carta home",
    "",
    ...(rows.length ? byObjectTables(groups) : ["(none)", ""]),
    "## Flow map — Carta slot ← OCF sources (the narrowest are the strongest upstream asks)",
    "",
    ...(rows.length ? flowMapLines(groups) : ["(none)"]),
    "",
  ];
  return lines.join("\n") + "\n";
}
