/**
 * OCF Core — generated markdown reports (membership ledger + R5 gap report).
 *
 * Shared by the build (scripts/derive-core-build, which WRITES them into core/)
 * and the CI check (scripts/derive-core-check, which RE-RENDERS and diffs them
 * against the committed copies) so the two can never disagree on the text — the
 * same drift guarantee the schema package already enjoys. Pure functions of a
 * `Derived`; no I/O.
 */
import { isPlainObject } from "./mapping-validator.js";
import { Derived } from "./core-pipeline.js";

// ---------------------------------------------------------------------------
// Membership ledger.
// ---------------------------------------------------------------------------

export function renderLedger(d: Derived): string {
  const admBy = new Map(d.admissibility.map((a) => [`${a.entity} ${a.variant}`, a]));
  const lines: string[] = [
    "# OCF Core — membership ledger (generated)",
    "",
    "GENERATED by scripts/derive-core-build — do not hand-edit; re-derived on every",
    "build and pinned by `npm run core:check`. One row per `(entity, variant, field)`.",
    "",
    "## Admissibility (§3)",
    "",
    "`alias-of X` marks an OCF compatibility wrapper (e.g. `PlanSecurity*`) that",
    "`allOf`-inherits `X` and declares no mapped fields of its own — its economic",
    "mapping lives in `X`. The core/payload counts are the wrapper's own (only",
    "`object_type`); `admissible` mirrors `X`, so a `✓` alias does have a target.",
    "",
    "| entity | variant | core | payload | admissible | blockers |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const a of d.admissibility) {
    const blk = a.blockers
      .map((b) =>
        b.why === "no-payload"
          ? "no-payload"
          : b.why === "alias"
          ? `alias-of ${b.referent}`
          : `${b.field}→${b.referent}`
      )
      .join(", ");
    lines.push(
      `| ${a.entity} | ${a.variant} | ${a.coreFieldCount} | ${a.payloadFieldCount} | ${
        a.admissible ? "✓" : "✗"
      } | ${blk || "—"} |`
    );
  }

  lines.push(
    "",
    "## Fields (§2)",
    "",
    "| entity | variant | field | class | loss/reason | detail |",
    "| --- | --- | --- | --- | --- | --- |"
  );
  for (const r of d.rows) {
    const v = r.verdict;
    const lr = v.class === "core" ? v.loss ?? "" : v.reason ?? "";
    const detail = [v.detail, v.review ? `⚑ ${v.review}` : ""].filter(Boolean).join("; ");
    const admitted = admBy.get(`${r.entity} ${r.variant}`)?.admissible ? "" : " ";
    lines.push(
      `| ${r.entity}${admitted} | ${r.variant} | ${r.field} | ${v.class} | ${lr} | ${detail} |`
    );
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// R5 gap report.
// ---------------------------------------------------------------------------

const BOOKKEEPING = new Set(["id", "object_type", "comments"]);

export function renderGapReport(d: Derived): string {
  const admissible = new Map(d.admissibility.map((a) => [`${a.entity} ${a.variant}`, a]));
  const reqByEntity = new Map(d.corpus.objects.map((o) => [o.entity, new Set(o.requiredFields)]));

  const lines: string[] = [
    "# OCF Core — gap report (R5, generated)",
    "",
    "GENERATED by scripts/derive-core-build. (a) OCF richness with no Carta home,",
    "per admissible entity, OCF-*required* casualties **bold**; (b) Carta object",
    "types no green mapping writes to.",
    "",
    "## (a) OCF richness dropped on fold-down",
    "",
  ];

  const nodes = new Map<string, typeof d.rows>();
  for (const r of d.rows) {
    const k = `${r.entity} ${r.variant}`;
    const list = nodes.get(k) ?? [];
    list.push(r);
    nodes.set(k, list);
  }

  for (const [key, frs] of [...nodes.entries()].sort()) {
    if (!admissible.get(key)?.admissible) continue;
    const out = frs.filter(
      (r) =>
        r.verdict.class === "out" && r.verdict.reason !== "heuristic" && !BOOKKEEPING.has(r.field)
    );
    if (out.length === 0) continue;
    const req = reqByEntity.get(frs[0]!.entity) ?? new Set<string>();
    const label =
      frs[0]!.variant === "—" ? frs[0]!.entity : `${frs[0]!.entity} [${frs[0]!.variant}]`;
    lines.push(`### ${label}`);
    for (const r of out.sort((a, b) => a.field.localeCompare(b.field))) {
      const tag = `${r.verdict.reason}${r.verdict.detail ? ` — ${r.verdict.detail}` : ""}`;
      const name = req.has(r.field) ? `**${r.field}** (OCF-required)` : r.field;
      lines.push(`- ${name}: ${tag}`);
    }
    lines.push("");
  }

  lines.push("## (b) Carta object types no green mapping writes to", "");
  const cartaDefs = (d.corpus.bundle as { $defs?: Record<string, unknown> }).$defs ?? {};
  const isObjectType = (def: unknown): boolean => {
    if (!isPlainObject(def) || !isPlainObject(def.properties)) return false;
    const keys = Object.keys(def.properties as Record<string, unknown>);
    return keys.length > 1 || (keys.length === 1 && keys[0] !== "value");
  };
  // Defensive value-type denylist: defs `isObjectType` would treat as objects
  // but that are really scalar/utility wrappers. Empty pending schema-owner
  // sign-off — the R5 audit found `isObjectType` mis-flags none of the current
  // set (e.g. Date, Interest are genuine objects). Add names here to exclude.
  const VALUE_TYPE_DENYLIST = new Set<string>([]);
  const untargeted = Object.entries(cartaDefs)
    .filter(
      ([name, def]) =>
        isObjectType(def) && !VALUE_TYPE_DENYLIST.has(name) && !d.corpus.targetedDefs.has(name)
    )
    .map(([name]) => name)
    .sort();

  // Partition the untargeted object defs so the report stops reading as N equal
  // "misses". A def is listed here iff it is object-typed and never the ROOT of
  // a green target pointer — but that covers three very different situations:
  //   b1 nested-covered — reached by `$ref` from a Carta object a green mapping
  //      DOES write to; covered indirectly, never a root target. Not a gap.
  //   b2 report roll-ups — Carta read-model aggregates (…Summary / …TransactionItem
  //      / stakeholder groupings); OCF is transaction-centric and has no source
  //      fact for them. Expected non-targets.
  //   b3 true gaps — the rest: OCF lacks the concept, or the def sits under a
  //      Carta parent that itself has no green mapping.
  const isReportRollup = (name: string) =>
    /(?:Summary|TransactionItem)$/.test(name) || name === "StakeholderGroup";
  const nestedCovered = untargeted.filter((n) => d.corpus.transitivelyCoveredDefs.has(n));
  const rest = untargeted.filter((n) => !d.corpus.transitivelyCoveredDefs.has(n));
  const rollups = rest.filter(isReportRollup);
  const trueGaps = rest.filter((n) => !isReportRollup(n));

  const emitList = (names: string[]) => {
    if (names.length === 0) lines.push("- (none)");
    else for (const name of names) lines.push(`- \`#/$defs/${name}\``);
    lines.push("");
  };

  lines.push(
    `${untargeted.length} of ${Object.keys(cartaDefs).length} Carta \`$defs\` are object-typed`,
    "and are not the **root** of any green mapping target. They split three ways:",
    ""
  );
  lines.push(
    `### (b1) Nested-covered — written to via a parent (${nestedCovered.length})`,
    "",
    "Reached by `$ref` from a Carta object a green mapping does write to, so the concept",
    "is covered indirectly; it is just never named as a root target. Not a gap.",
    ""
  );
  emitList(nestedCovered);
  lines.push(
    `### (b2) Carta report roll-ups — no OCF source fact (${rollups.length})`,
    "",
    "Carta read-model aggregates (…Summary / …TransactionItem / stakeholder groupings).",
    "OCF records the leaf events, never the derived container. Expected non-targets.",
    ""
  );
  emitList(rollups);
  lines.push(
    `### (b3) True gaps — OCF lacks the concept, or the parent is unmapped (${trueGaps.length})`,
    "",
    "The real candidates: OCF has no equivalent (e.g. phantom-equity / profits-interest),",
    "or the def sits under a Carta parent that itself has no green mapping.",
    ""
  );
  emitList(trueGaps);
  return lines.join("\n") + "\n";
}
