/**
 * OCF Core — §4 schema emitter.
 *
 * Renders the Core JSON Schema: one `$def` per Core-admissible `(entity, variant)`,
 * pruned to its `core` fields, every value INLINED into OCF grammar so the result
 * is self-contained (no external `$ref`) and assertable:
 *   - Numeric / Percentage / CurrencyCode / Md5 already ship `pattern`s → reused.
 *   - Date ships only `format: date` (annotation-only under draft-07) → the emitter
 *     SYNTHESISES `^\d{4}-\d{2}-\d{2}$` so a time-of-day is actually rejected.
 *   - enums inline their value set; composite types (Monetary, Ratio, …) recurse.
 *
 * `required: []` on every entity: the Carta fold declares nothing required (§3
 * finding — every Carta target is `required:[]`), so the fold-driven required set
 * is empty. An instance valid against this schema is, by construction, a Core
 * instance whose values are in OCF grammar — guaranteed-foldable on values.
 */
import { detectEnumValues } from "./enum-detection.js";
import { Registry } from "./registry.js";
import { isPlainObject } from "./mapping-validator.js";
import { resolveSource } from "./core-classifier.js";

const DATE_PATTERN = "^\\d{4}-\\d{2}-\\d{2}$";

/** Render one OCF source node into an inlined, OCF-grammar-constrained Core node. */
export function renderNode(
  srcRaw: unknown,
  registry: Registry,
  depth = 0
): Record<string, unknown> {
  if (depth > 12) return {};
  const n = resolveSource(srcRaw, registry);
  if (!isPlainObject(n)) return {};

  // Array first — detectEnumValues would otherwise collapse an array-of-enum.
  if (n.type === "array") {
    return { type: "array", items: renderNode(n.items, registry, depth + 1) };
  }

  const enumVals = detectEnumValues(n, registry);
  if (enumVals) return { type: "string", enum: enumVals };

  // Composite type (object with its own properties): recurse, keep its required.
  // OCF scalar type files carry boilerplate `properties: {}`; an empty object is
  // not a composite, so require at least one property before recursing.
  if (isPlainObject(n.properties) && Object.keys(n.properties).length > 0) {
    const props = n.properties as Record<string, unknown>;
    const rendered: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(props)) rendered[k] = renderNode(v, registry, depth + 1);
    const required = Array.isArray(n.required)
      ? n.required.filter((r): r is string => typeof r === "string" && r in rendered)
      : [];
    const node: Record<string, unknown> = { type: "object", additionalProperties: false };
    node.properties = rendered;
    if (required.length) node.required = required;
    return node;
  }

  // Scalar leaf.
  if (typeof n.pattern === "string") {
    return { type: typeof n.type === "string" ? n.type : "string", pattern: n.pattern };
  }
  if (n.format === "date") return { type: "string", pattern: DATE_PATTERN };
  if (n.format === "date-time") return { type: "string", format: "date-time" };
  return { type: typeof n.type === "string" ? n.type : "string" };
}

export interface CoreField {
  field: string;
  srcRaw: unknown;
  description?: string;
}

export interface CoreEntity {
  /** `$def` name: Entity, or Entity__Variant when polymorphic. */
  defName: string;
  entity: string;
  variant: string;
  fields: CoreField[];
}

/** Assemble the full Core JSON Schema from the admissible entities. */
export function emitCoreSchema(
  entities: CoreEntity[],
  registry: Registry
): Record<string, unknown> {
  const defs: Record<string, unknown> = {};
  for (const e of [...entities].sort((a, b) => a.defName.localeCompare(b.defName))) {
    const properties: Record<string, unknown> = {};
    for (const f of [...e.fields].sort((a, b) => a.field.localeCompare(b.field))) {
      const node = renderNode(f.srcRaw, registry);
      if (f.description) node.description = f.description;
      properties[f.field] = node;
    }
    defs[e.defName] = {
      type: "object",
      title: e.entity + (e.variant === "—" ? "" : ` (${e.variant})`),
      properties,
      // Fold-driven required set; the Carta fold requires nothing (§3).
      required: [],
      additionalProperties: false,
    };
  }
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    $id: "https://opencaptablecoalition.com/ocf-core/v0/core.schema.json",
    title: "OCF Core (derived)",
    description:
      "GENERATED by scripts/derive-core-build — do not hand-edit. One $def per " +
      "Core-admissible (entity, variant), pruned to fields that fold losslessly to " +
      "Carta, values inlined into OCF grammar. required:[] because the Carta fold " +
      "declares nothing required (see docs/ocf-core-spec.md §3).",
    oneOf: Object.keys(defs)
      .sort()
      .map((d) => ({ $ref: `#/$defs/${d}` })),
    $defs: defs,
  };
}
