#!/usr/bin/env node
/**
 * OCF Core — §4 build (the generator).
 *
 * Runs the derive pipeline (scripts/lib/core-pipeline) and EMITS the generated
 * artifacts for the admissible set, all generated / never hand-edited:
 *   - core.schema.json — the Core JSON Schema (drift-gated by core:check)
 *   - core-ledger.md   — the membership ledger (one row per entity,variant,field)
 *   - core-gaps.md     — the R5 gap report
 * Writes into --out-dir (default: ./core) and prints a summary + a sample $def.
 *
 *   npm run core:build                       # emit to ./core, print summary
 *   npm run core:build -- --out-dir /tmp/x   # emit elsewhere
 *   npm run core:build -- --sample StockIssuance
 */
import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";

import { isPlainObject } from "./lib/mapping-validator.js";
import { deriveCore, Derived } from "./lib/core-pipeline.js";

async function main(argv: { outDir: string; sample: string }): Promise<number> {
  const repoRoot = process.cwd();
  const derived = await deriveCore(repoRoot);

  await mkdir(argv.outDir, { recursive: true });
  const schemaPath = path.join(argv.outDir, "core.schema.json");
  const ledgerPath = path.join(argv.outDir, "core-ledger.md");
  const gapsPath = path.join(argv.outDir, "core-gaps.md");
  await writeFile(schemaPath, JSON.stringify(derived.schema, null, 2) + "\n", "utf8");
  await writeFile(ledgerPath, renderLedger(derived), "utf8");
  await writeFile(gapsPath, renderGapReport(derived), "utf8");

  const defCount = Object.keys((derived.schema.$defs as Record<string, unknown>) ?? {}).length;
  console.log("OCF Core — §4 build");
  console.log("=".repeat(70));
  console.log(`Admissible (entity,variant): ${derived.coreEntities.length}  →  ${defCount} $defs`);
  console.log(`  core.schema.json  → ${schemaPath}`);
  console.log(`  core-ledger.md    → ${ledgerPath}`);
  console.log(`  core-gaps.md      → ${gapsPath}`);

  const sampleDef = derived.coreEntities.find((e) => e.defName.includes(argv.sample));
  if (sampleDef) {
    const defs = derived.schema.$defs as Record<string, unknown>;
    console.log(`\nSample $def — ${sampleDef.defName}:`);
    console.log(JSON.stringify(defs[sampleDef.defName], null, 2));
  }
  return 0;
}

// ---------------------------------------------------------------------------
// Membership ledger.
// ---------------------------------------------------------------------------

function renderLedger(d: Derived): string {
  const admBy = new Map(d.admissibility.map((a) => [`${a.entity} ${a.variant}`, a]));
  const lines: string[] = [
    "# OCF Core — membership ledger (generated)",
    "",
    "GENERATED by scripts/derive-core-build — do not hand-edit; re-derived on every",
    "build and pinned by `npm run core:check`. One row per `(entity, variant, field)`.",
    "",
    "## Admissibility (§3)",
    "",
    "| entity | variant | core | payload | admissible | blockers |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const a of d.admissibility) {
    const blk = a.blockers
      .map((b) => (b.why === "no-payload" ? "no-payload" : `${b.field}→${b.referent}`))
      .join(", ");
    lines.push(
      `| ${a.entity} | ${a.variant} | ${a.coreFieldCount} | ${a.payloadFieldCount} | ${
        a.admissible ? "✓" : "✗"
      } | ${blk || "—"} |`
    );
  }

  lines.push(
    "",
    "## Fields (§2)",
    "",
    "| entity | variant | field | class | loss/reason | detail |",
    "| --- | --- | --- | --- | --- | --- |"
  );
  for (const r of d.rows) {
    const v = r.verdict;
    const lr = v.class === "core" ? v.loss ?? "" : v.reason ?? "";
    const detail = [v.detail, v.review ? `⚑ ${v.review}` : ""].filter(Boolean).join("; ");
    const admitted = admBy.get(`${r.entity} ${r.variant}`)?.admissible ? "" : " ";
    lines.push(
      `| ${r.entity}${admitted} | ${r.variant} | ${r.field} | ${v.class} | ${lr} | ${detail} |`
    );
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// R5 gap report.
// ---------------------------------------------------------------------------

const BOOKKEEPING = new Set(["id", "object_type", "comments"]);

function renderGapReport(d: Derived): string {
  const admissible = new Map(d.admissibility.map((a) => [`${a.entity} ${a.variant}`, a]));
  const reqByEntity = new Map(d.corpus.objects.map((o) => [o.entity, new Set(o.requiredFields)]));

  const lines: string[] = [
    "# OCF Core — gap report (R5, generated)",
    "",
    "GENERATED by scripts/derive-core-build. (a) OCF richness with no Carta home,",
    "per admissible entity, OCF-*required* casualties **bold**; (b) Carta object",
    "types no green mapping writes to.",
    "",
    "## (a) OCF richness dropped on fold-down",
    "",
  ];

  const nodes = new Map<string, typeof d.rows>();
  for (const r of d.rows) {
    const k = `${r.entity} ${r.variant}`;
    const list = nodes.get(k) ?? [];
    list.push(r);
    nodes.set(k, list);
  }

  for (const [key, frs] of [...nodes.entries()].sort()) {
    if (!admissible.get(key)?.admissible) continue;
    const out = frs.filter(
      (r) =>
        r.verdict.class === "out" && r.verdict.reason !== "heuristic" && !BOOKKEEPING.has(r.field)
    );
    if (out.length === 0) continue;
    const req = reqByEntity.get(frs[0]!.entity) ?? new Set<string>();
    const label =
      frs[0]!.variant === "—" ? frs[0]!.entity : `${frs[0]!.entity} [${frs[0]!.variant}]`;
    lines.push(`### ${label}`);
    for (const r of out.sort((a, b) => a.field.localeCompare(b.field))) {
      const tag = `${r.verdict.reason}${r.verdict.detail ? ` — ${r.verdict.detail}` : ""}`;
      const name = req.has(r.field) ? `**${r.field}** (OCF-required)` : r.field;
      lines.push(`- ${name}: ${tag}`);
    }
    lines.push("");
  }

  lines.push("## (b) Carta object types no green mapping targets", "");
  const cartaDefs = (d.corpus.bundle as { $defs?: Record<string, unknown> }).$defs ?? {};
  const isObjectType = (def: unknown): boolean => {
    if (!isPlainObject(def) || !isPlainObject(def.properties)) return false;
    const keys = Object.keys(def.properties as Record<string, unknown>);
    return keys.length > 1 || (keys.length === 1 && keys[0] !== "value");
  };
  const untargeted = Object.entries(cartaDefs)
    .filter(([name, def]) => isObjectType(def) && !d.corpus.targetedDefs.has(name))
    .map(([name]) => name)
    .sort();
  lines.push(
    `${untargeted.length} of ${Object.keys(cartaDefs).length} Carta \`$defs\` are object-typed`,
    "and unreferenced by any green mapping target (candidate Carta concepts OCF may",
    "lack, or simply not-yet-mapped):",
    ""
  );
  for (const name of untargeted) lines.push(`- \`#/$defs/${name}\``);
  return lines.join("\n") + "\n";
}

const parsed = yargs(hideBin(process.argv))
  .scriptName("core:build")
  .option("out-dir", {
    type: "string",
    describe: "Directory to write artifacts into (default ./core)",
  })
  .option("sample", {
    type: "string",
    default: "StockIssuance",
    describe: "Entity to print a sample $def for",
  })
  .strict()
  .help()
  .parseSync();

main({
  outDir:
    typeof parsed["out-dir"] === "string"
      ? (parsed["out-dir"] as string)
      : path.join(process.cwd(), "core"),
  sample: typeof parsed.sample === "string" ? parsed.sample : "StockIssuance",
}).then(
  (code) => process.exit(code),
  (err) => {
    console.error(err);
    process.exit(1);
  }
);
