#!/usr/bin/env node
import path from "node:path";
import { readdir, readFile, writeFile } from "node:fs/promises";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";

import {
  deriveMappingCoverage,
  formatCoverage,
  MappingFieldState,
} from "./lib/mapping-coverage.js";
import { parseMappingDocument } from "./lib/mapping-parser.js";
import { RawSchema } from "./lib/registry.js";

const MAPPING_DIRS = ["objects", "types"] as const;
const OUTPUT = "docs/mapping-coverage.md";

interface MappingRecord {
  rel: string;
  frontmatter: Record<string, unknown>;
  mapping: Record<string, unknown>;
  sourceSchema: RawSchema;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function statusOf(mapping: Record<string, unknown>): string {
  return typeof mapping.status === "string" ? mapping.status : "?";
}

function symbol(state: MappingFieldState): string {
  switch (state) {
    case "mapped":
      return "🟩";
    case "todo":
      return "🟨";
    case "missing":
      return "⬜";
    case "invalid":
      return "🟥";
  }
}

function heatmap(fields: Record<string, MappingFieldState>): string {
  return Object.entries(fields)
    .map(([name, state]) => {
      const label = `${name}: ${state}`;
      return `<span title="${escapeHtml(label)}" aria-label="${escapeHtml(label)}">${symbol(
        state
      )}</span>`;
    })
    .join("");
}

function issues(fields: Record<string, MappingFieldState>): string {
  const entries = Object.entries(fields).filter(([, state]) => state !== "mapped");
  if (entries.length === 0) return "—";
  return entries.map(([name, state]) => `${state}: \`${name}\``).join(", ");
}

async function collectMappings(repoRoot: string): Promise<MappingRecord[]> {
  const files: string[] = [];
  for (const dir of MAPPING_DIRS) {
    const abs = path.join(repoRoot, dir);
    for (const entry of await readdir(abs, { recursive: true, withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith(".mapping.md")) continue;
      const parent =
        (entry as unknown as { parentPath?: string; path?: string }).parentPath ??
        (entry as unknown as { path?: string }).path ??
        abs;
      files.push(path.relative(repoRoot, path.join(parent, entry.name)));
    }
  }

  const records: MappingRecord[] = [];
  for (const rel of files.sort()) {
    const markdown = await readFile(path.join(repoRoot, rel), "utf8");
    const parsed = parseMappingDocument(markdown, rel);
    const schemaRel = rel.replace(/\.mapping\.md$/, ".schema.json");
    const sourceSchema = JSON.parse(
      await readFile(path.join(repoRoot, schemaRel), "utf8")
    ) as RawSchema;
    records.push({ ...parsed, rel, sourceSchema });
  }
  return records;
}

function render(records: MappingRecord[]): string {
  const rows: string[] = [];
  const incomplete: string[] = [];
  let mapped = 0;
  let total = 0;

  for (const record of records) {
    const coverage = deriveMappingCoverage(record.mapping, record.sourceSchema);
    const status = statusOf(record.mapping);
    const link = `[\`${record.rel}\`](../${record.rel})`;
    const slices = coverage.polymorphic
      ? Object.entries(coverage.variants ?? {}).map(([label, slice]) => ({ label, slice }))
      : coverage.overall
      ? [{ label: "—", slice: coverage.overall }]
      : [];

    for (const { label, slice } of slices) {
      mapped += slice.mapped;
      total += slice.total;
      const labelWithVariant = label === "—" ? link : `${link} · ${label}`;
      rows.push(
        `| ${labelWithVariant} | ${status} | ${formatCoverage(slice)} | ${heatmap(
          slice.fields
        )} | ${issues(slice.fields)} |`
      );
      if (Object.values(slice.fields).some((state) => state !== "mapped")) {
        incomplete.push(`| ${labelWithVariant} | ${issues(slice.fields)} |`);
      }
    }
  }

  const complete = rows.filter((row) => row.includes("| complete |")).length;
  const totalRows = rows.length;
  const incompleteRows = totalRows - complete;
  const incompleteLabel = incompleteRows === 1 ? "slice" : "slices";
  const lines = [
    "# Mapping coverage heatmap (generated)",
    "",
    "Generated by `npm run mapping:coverage`. Coverage is derived from each source schema and its mapping entries; mapping authors do not maintain counters.",
    "",
    "Legend: 🟩 valid mapping entry · 🟨 TODO · ⬜ missing entry · 🟥 invalid entry. Hover a cell in a rendered Markdown viewer to see its field name and state.",
    "",
    `**${records.length} mapping files · ${totalRows} mapping slices · ${mapped}/${total} derived field entries mapped · ${incompleteRows} ${incompleteLabel} need attention**`,
    "",
    "## Heatmap",
    "",
    "| Mapping | Status | Derived coverage | Fields | Needs attention |",
    "| --- | --- | ---: | --- | --- |",
    ...rows,
    "",
    "## Incomplete slices",
    "",
    incomplete.length
      ? ["| Mapping | Fields to resolve |", "| --- | --- |", ...incomplete].join("\n")
      : "No incomplete mapping slices.",
    "",
  ];
  return lines.join("\n");
}

async function main(args: { check: boolean; output: string }): Promise<number> {
  const repoRoot = process.cwd();
  const records = await collectMappings(repoRoot);
  const expected = render(records);
  const output = path.resolve(repoRoot, args.output);

  if (args.check) {
    let actual: string;
    try {
      actual = await readFile(output, "utf8");
    } catch (err) {
      console.error(
        `Mapping coverage heatmap is missing at ${args.output}: ${(err as Error).message}`
      );
      return 1;
    }
    if (actual !== expected) {
      console.error(
        `Mapping coverage heatmap is stale at ${args.output}; run \`npm run mapping:coverage\`.`
      );
      return 1;
    }
    console.log(`Mapping coverage heatmap: OK (${args.output})`);
    return 0;
  }

  await writeFile(output, expected, "utf8");
  console.log(`Wrote ${args.output}`);
  return 0;
}

const parsed = yargs(hideBin(process.argv))
  .scriptName("mapping:coverage")
  .option("check", {
    type: "boolean",
    default: false,
    describe: "Check that the committed heatmap matches a fresh derivation",
  })
  .option("output", {
    type: "string",
    default: OUTPUT,
    describe: "Markdown output path, relative to the repository root",
  })
  .strict()
  .help()
  .parseSync();

main({
  check: Boolean(parsed.check),
  output: typeof parsed.output === "string" ? parsed.output : OUTPUT,
}).then(
  (code) => process.exit(code),
  (err) => {
    console.error(err);
    process.exit(1);
  }
);
