#!/usr/bin/env node
/**
 * OCF Core — lossy-home inventory (step 1, a discussion artifact — NOT gated).
 *
 * Re-cuts the SAME derived ledger the build produces (one `deriveCore` call; no
 * re-load, no re-classify) into the distinction that matters for a rich Core —
 * LOSSY HOME (the field HAS a Carta target but the fold loses fidelity:
 * `existence-loss` structure/array→scalar, or `heuristic` combine/split/computed)
 * vs NO HOME (`no-destination`, Carta has no field at all) — and presents the flow:
 *
 *   Overview — a mermaid diagram of OCF objects → the Carta objects they flow to.
 *   A. Lossy home GROUPED BY OCF OBJECT, each field showing where it flows in Carta.
 *   B. Flow map — the inverse: one entry per Carta slot, listing every OCF property
 *      that lands on it, so convergence (many→one reverse edges) is obvious.
 *   C. No home, grouped by object, for contrast (also in core-gaps.md).
 *
 * The visual layer (mermaid, grouping, flow map) is shared with the upstream and
 * gap reports via scripts/lib/report-flow. OCF bookkeeping is excluded; variants
 * that map identically are collapsed.
 *
 *   npm run core:lossy            # write docs/core-lossy-inventory.md + print summary
 */
import path from "node:path";
import { writeFile } from "node:fs/promises";

import { deriveCore, RICH_PROFILE } from "./lib/core-pipeline.js";
import { BOOKKEEPING, buildTargetIndex } from "./lib/report-helpers.js";
import {
  FlowRow,
  byObjectTables,
  flowMapLines,
  groupByEntity,
  mermaidFlow,
} from "./lib/report-flow.js";

const OUT_FILE = "docs/core-lossy-inventory.md";
// "Lossy home" = the reasons the rich profile promotes to members (single source
// of truth: RICH_PROFILE.memberReasons); "no home" (no-destination) is separate.
const LOSSY_HOME = RICH_PROFILE.memberReasons;

async function main(): Promise<number> {
  const d = await deriveCore(process.cwd());
  const admBy = new Map(d.admissibility.map((a) => [`${a.entity} ${a.variant}`, a]));
  const reqBy = new Map(d.corpus.objects.map((o) => [o.entity, new Set(o.requiredFields)]));
  const targetOf = buildTargetIndex(d.corpus.objects);

  const lossy: FlowRow[] = [];
  const nohome: FlowRow[] = [];
  for (const r of d.rows) {
    if (r.verdict.class !== "out" || BOOKKEEPING.has(r.field)) continue;
    const reason = r.verdict.reason;
    if (reason === undefined) continue;
    const row: FlowRow = {
      entity: r.entity,
      variant: r.variant,
      field: r.field,
      reason,
      detail: r.verdict.detail ?? "",
      target: targetOf.get(`${r.entity} ${r.variant} ${r.field}`) ?? "—",
      ocfRequired: reqBy.get(r.entity)?.has(r.field) ?? false,
      admissible: admBy.get(`${r.entity} ${r.variant}`)?.admissible ?? false,
    };
    if (LOSSY_HOME.has(reason)) lossy.push(row);
    else if (reason === "no-destination") nohome.push(row);
  }

  await writeFile(path.join(process.cwd(), OUT_FILE), render(lossy, nohome), "utf8");

  const reqLossy = lossy.filter((r) => r.ocfRequired).length;
  const onAdmissible = new Set(lossy.filter((r) => r.admissible).map((r) => r.entity)).size;
  console.log("OCF Core — lossy-home inventory");
  console.log("=".repeat(60));
  console.log(`A. lossy home (has a target, loses fidelity): ${lossy.length} rows`);
  console.log(`   · ${reqLossy} are OCF-REQUIRED fields`);
  console.log(`   · touching ${onAdmissible} currently-admissible entit(y/ies)`);
  console.log(`B. no home (no Carta target): ${nohome.length} rows`);
  console.log(`\nWritten to ${OUT_FILE}`);
  return 0;
}

function render(lossy: FlowRow[], nohome: FlowRow[]): string {
  const groupedLossy = groupByEntity(lossy);
  const noHomeGroups = groupByEntity(nohome);
  const reqCount = lossy.filter((r) => r.ocfRequired).length;

  const lines: string[] = [
    "# OCF Core — lossy-home inventory (generated, discussion artifact)",
    "",
    "GENERATED by `npm run core:lossy` from the same derived ledger as the build.",
    "NOT drift-gated — this is an analysis input for the rich-Core work, not a contract.",
    "",
    "Fields that today fall **out** of Core, split by whether Carta offers a home at all.",
    "`OCF-req` marks fields OCF itself requires — a lossy home on a required field is the",
    "strongest rich-Core / upstream-OCF signal. The **overview diagram** shows the whole flow;",
    "**A** breaks it down per OCF object; **B** inverts it (per Carta slot); **C** is no-home.",
    "",
    "## Overview — flow diagrams, one per connected group",
    "",
    "Objects that exchange properties — directly, or transitively via a shared Carta target —",
    "are drawn in the SAME diagram; unrelated mappings get their own. OCF source objects are",
    "green (in strict Core) or dashed grey (not yet admissible); each edge is labelled with the",
    "field count. Groups are largest-first — the opener is the reverse-edge lineage converging",
    "on the two `…PrecededBy`.",
    "",
    ...mermaidFlow(groupedLossy),
    "",
    `## A. Lossy home — by OCF object, flowing to Carta (${lossy.length} (entity,variant,field) rows across ${groupedLossy.length} objects; ${reqCount} OCF-required)`,
    "",
    "Each field HAS a Carta home but the fold loses fidelity: `existence-loss` = the shape",
    "collapses (object/array → scalar); `heuristic` = a non-1:1 transform (combine/split/computed).",
    "A field mapping the same way across variants is shown once, the variants listed.",
    "",
    ...byObjectTables(groupedLossy),
    `## B. Flow map — Carta slot ← OCF sources`,
    "",
    "Sorted by fan-in. Slots with several sources are where distinct OCF properties **converge**",
    "onto one Carta field — most visibly the reverse-edge lineage collapsing onto `…PrecededBy.securities`.",
    "",
    ...flowMapLines(groupedLossy),
    "",
    `## C. No home — no Carta target at all (${nohome.length} across ${noHomeGroups.length} objects)`,
    "",
    "A different animal: Carta has no field to hold these (also in core-gaps.md §a). NOT what",
    "rich-Core recovers — listed for contrast.",
    "",
  ];
  for (const g of noHomeGroups) {
    const fields = g.fields.map((f) => (f.ocfRequired ? `**${f.field}**` : f.field)).join(", ");
    lines.push(`- **${g.entity}**${g.admissible ? "" : " *(not yet admissible)*"} — ${fields}`);
  }
  lines.push("");
  return lines.join("\n") + "\n";
}

main().then(
  (code) => process.exit(code),
  (err) => {
    console.error(err);
    process.exit(1);
  }
);
